### ISSUE TITLE
Google scholar url error

### ISSUE THREAD

**Issue by AMindToThink** [alphaXiv/feedback#14]
When I try inputting my google scholar url when signing up, https://scholar.google.com/citations?user=_BvDtiUAAAAJ&hl=en, I get an error `An error occurred while connecting to Google Scholar. Please try again.`. Is this the wrong url? How can I fix this?

**Comment by junkim100** [comment]
Same issue with this url: https://scholar.google.com/citations?user=ZE8

**Comment by SeaingAnt** [comment]
Same with https://scholar.google.com/citations?user=bKy_YlkAAAAJ&hl=en
Plus, also using ORCID does not work

**Comment by sox8502** [comment]
@AMindToThink @junkim100 @SeaingAnt syncing authorship with Google Scholar should now work. Please let me know if it doesn't.

**Comment by junkim100** [comment]
<img width="460" height="488" alt="Image" src="https://github.com/user-attachments/assets/36f0049b-fa6d-4f6b-ad2a-d6b3656323ce" />

Unfortunately, still doesn't work.

**Comment by lino-levan** [comment]
@junkim100 I don't see user ZE8 on google scholar. Are you sure that's a valid user? Typically google scholar user ids are much longer.

**Comment by junkim100** [comment]
Ah my mistake. It works well now. Thanks

**Comment by lino-levan** [comment]
Thanks for checking! Closing this out unless someone still has this issue.

**Comment by huanranchen** [comment]
> Thanks for checking! Closing this out unless someone still has this issue.

@lino-levan 

Hi~ I still have the issue....

https://scholar.google.com/citations?user=QYsKXccAAAAJ

I have checked the link, it is correct....

<img width="2832" height="1198" alt="Image" src="https://github.com/user-attachments/assets/775a0734-7988-4e05-a0a7-f46150ac2d3b" />


Interestingly, I can link my classmate's google scholar........ Is there anything special in my Google Scholar :(

**Comment by lino-levan** [comment]
Thanks for sharing, will get someone to investigate

**Comment by lino-levan** [comment]
Thank you for your patience, we have rewrite our google scholar integration from scratch and this is now fixed.
